# Pytorch 실습

In [3]:
import torch

# GPU 이용가능한지 체크하는 코드
torch.cuda.is_available()

True

In [4]:
torch.__version__

'2.8.0+cu126'

In [5]:
torch.tensor(5)

tensor(5)

In [6]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [7]:
torch.tensor([[1,2,3],
              [4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
data = [1,2,3,4,5]
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [11]:
# numpy의 array 와 tensor 도 호환
import numpy as np
data = np.array([1,2,3,4,5])
torch.tensor(data)

tensor([1, 2, 3, 4, 5])

In [13]:
# 안이 전부 1로 채워진 tensor 어레이 만들어줌

torch.ones(5)
torch.ones(3,5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:
torch.ones(512, 512)

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [15]:
torch.zeros(512,512)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
torch.arange(1, 10, 2)

tensor([1, 3, 5, 7, 9])

In [19]:
data = torch.rand(3,3,3)
data

tensor([[[0.7479, 0.8291, 0.2631],
         [0.8429, 0.0685, 0.9348],
         [0.8986, 0.8485, 0.6163]],

        [[0.1617, 0.5410, 0.0558],
         [0.3013, 0.8208, 0.0901],
         [0.7292, 0.1254, 0.5109]],

        [[0.4807, 0.3215, 0.7407],
         [0.0752, 0.6472, 0.3535],
         [0.3818, 0.0122, 0.5195]]])

## 데이터의 shape 변환 -> torch.tensor().view() 사용

In [25]:
data.view(9,3)
data.view(3,9)
data.view(27)

tensor([0.7479, 0.8291, 0.2631, 0.8429, 0.0685, 0.9348, 0.8986, 0.8485, 0.6163,
        0.1617, 0.5410, 0.0558, 0.3013, 0.8208, 0.0901, 0.7292, 0.1254, 0.5109,
        0.4807, 0.3215, 0.7407, 0.0752, 0.6472, 0.3535, 0.3818, 0.0122, 0.5195])

In [27]:
data.view(9, -1)

tensor([[0.7479, 0.8291, 0.2631],
        [0.8429, 0.0685, 0.9348],
        [0.8986, 0.8485, 0.6163],
        [0.1617, 0.5410, 0.0558],
        [0.3013, 0.8208, 0.0901],
        [0.7292, 0.1254, 0.5109],
        [0.4807, 0.3215, 0.7407],
        [0.0752, 0.6472, 0.3535],
        [0.3818, 0.0122, 0.5195]])

In [ ]:
data.view(-1) # data를 한 줄로 쭉 펴준다.

tensor([0.7479, 0.8291, 0.2631, 0.8429, 0.0685, 0.9348, 0.8986, 0.8485, 0.6163,
        0.1617, 0.5410, 0.0558, 0.3013, 0.8208, 0.0901, 0.7292, 0.1254, 0.5109,
        0.4807, 0.3215, 0.7407, 0.0752, 0.6472, 0.3535, 0.3818, 0.0122, 0.5195])

In [31]:
# tensor의 shape 확인
data.shape

torch.Size([3, 3, 3])

In [32]:
# tensor의 dimension 확인
data.dim

<function Tensor.dim>

In [34]:
# 학습시킬 때 data의 타입도 맞춰줘야한다.
data.dtype

torch.float32

In [35]:
torch.cuda.is_available()

True

In [36]:
torch.cuda.device_count()

1

In [ ]:
torch.cuda.get_device_name()

'NVIDIA GeForce RTX 4070 Laptop GPU'

In [38]:
device = torch.device("cuda:1")

In [39]:
data = torch.tensor([1,2,3])
data

tensor([1, 2, 3])

In [41]:
data.to('cuda') #학습할 데이터도 모델이 있는 gpu로 옮겨야한다.

tensor([1, 2, 3], device='cuda:0')

In [44]:
data1 = torch.tensor([1,2,3]).cuda() # gpu 메모리로 옮기는 방법2
data1

tensor([1, 2, 3], device='cuda:0')

In [45]:
data1.to('cpu')

tensor([1, 2, 3])

### tensor 데이터 끼리의 연산

In [49]:
data = data.to('cuda')
data + data1 # gpu와 cpu 각각에 있는 데이터는 연산 불가

tensor([2, 4, 6], device='cuda:0')

In [50]:
data * data1

tensor([1, 4, 9], device='cuda:0')

In [51]:
data - data1

tensor([0, 0, 0], device='cuda:0')

In [53]:
data = torch.tensor([[1,2,3], [4,5,6]])
data

tensor([[1, 2, 3],
        [4, 5, 6]])

In [55]:
data.min()
data.max()

tensor(6)

In [57]:
data.min(dim=0)

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))

In [ ]:
data.min(dim=1)

torch.return_types.min(
values=tensor([1, 4]),
indices=tensor([0, 0]))

In [60]:
data.dtype

torch.int64

In [61]:
data = data.type(torch.float32)
data.dtype

torch.float32

In [63]:
data.mean()

tensor(3.5000)

### 차원을 늘리기

In [67]:
image = torch.rand(3, 128, 128)

image = image.view(1, 3, 128, 128)
image

tensor([[[[0.1617, 0.6269, 0.0599,  ..., 0.7870, 0.4571, 0.6253],
          [0.3243, 0.5195, 0.4345,  ..., 0.4605, 0.8628, 0.2828],
          [0.8705, 0.2782, 0.5929,  ..., 0.3302, 0.9118, 0.6926],
          ...,
          [0.4136, 0.4488, 0.8385,  ..., 0.2555, 0.3795, 0.5559],
          [0.4596, 0.9632, 0.5100,  ..., 0.8798, 0.7554, 0.2945],
          [0.8968, 0.4431, 0.9036,  ..., 0.6305, 0.4254, 0.7225]],

         [[0.7864, 0.4086, 0.8856,  ..., 0.3436, 0.3384, 0.5089],
          [0.2690, 0.4780, 0.0697,  ..., 0.0909, 0.9994, 0.5440],
          [0.3037, 0.5861, 0.9332,  ..., 0.0580, 0.5115, 0.4744],
          ...,
          [0.8375, 0.7351, 0.8268,  ..., 0.3862, 0.3890, 0.9078],
          [0.1256, 0.9616, 0.1188,  ..., 0.4397, 0.6184, 0.6059],
          [0.6023, 0.1835, 0.8831,  ..., 0.3445, 0.1092, 0.2381]],

         [[0.5994, 0.8986, 0.1817,  ..., 0.3822, 0.1205, 0.8356],
          [0.8078, 0.5636, 0.9207,  ..., 0.1836, 0.4975, 0.9514],
          [0.3047, 0.2630, 0.8796,  ..., 0

In [72]:

image = torch.rand(3, 128, 128)
image = image.unsqueeze(dim=0) # 원래 차원보다 하나의 차원을 늘려주는 역할

image.shape

torch.Size([1, 3, 128, 128])

In [79]:
data = torch.rand(1, 128, 128)
data = data.squeeze()
data.shape

torch.Size([128, 128])

## 보스턴 데이터로 딥러닝 모델 설계

In [80]:
import pandas as pd

df = pd.read_csv("../../data_resources/boston.csv")
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0


In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [88]:
x_train = df.drop(["MEDV"], axis=1).values #numpy 배열로
# x_train = torch.tensor(x_train) #numpy 배열을 tensor로
x_train = torch.FloatTensor(x_train) # tensor로 바꾸면서 자동으로 float로

In [89]:
x_train.shape

torch.Size([506, 13])

In [90]:
y_train = torch.FloatTensor(df.iloc[:, -1].values)
y_train.shape

torch.Size([506])

In [108]:
import torch.nn as nn
from torch.optim.adam import Adam

model = nn.Sequential(
    nn.Linear(13, 100),
    nn.ReLU(),
    nn.Linear(100, 50),
    nn.ReLU(),
    nn.Linear(50, 1)
)

model


Sequential(
  (0): Linear(in_features=13, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=50, bias=True)
  (3): ReLU()
  (4): Linear(in_features=50, out_features=1, bias=True)
)

In [92]:
df.shape

(506, 14)

In [94]:
model.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=13, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=50, bias=True)
  (3): ReLU()
  (4): Linear(in_features=50, out_features=1, bias=True)
)>

In [98]:
for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.0500, -0.1204,  0.0564,  ...,  0.1213,  0.1979,  0.2350],
        [-0.1480,  0.0269, -0.0648,  ..., -0.1906,  0.2439, -0.0348],
        [-0.0938,  0.1702,  0.1266,  ...,  0.2504,  0.0055,  0.2589],
        ...,
        [ 0.1408, -0.1194,  0.0940,  ..., -0.1147,  0.2608, -0.0161],
        [ 0.2022,  0.2424, -0.0818,  ...,  0.0359,  0.1891, -0.2009],
        [ 0.2088, -0.1858, -0.1837,  ..., -0.2672,  0.2638,  0.2110]],
       requires_grad=True)
Parameter containing:
tensor([-0.1268, -0.0083, -0.2219,  0.2092, -0.1781, -0.1676, -0.1339,  0.2422,
         0.0799, -0.0199, -0.0511, -0.2732,  0.0543,  0.1226,  0.1326,  0.2126,
        -0.1069, -0.0114, -0.0473,  0.1668,  0.2672, -0.1315,  0.1911, -0.2077,
         0.1376,  0.1584, -0.2516,  0.2211, -0.0815, -0.0084,  0.0354,  0.2440,
        -0.2280, -0.2749, -0.0522, -0.0977, -0.2678,  0.0147,  0.0978, -0.0271,
        -0.0244, -0.2639,  0.1006,  0.2068,  0.2042, -0.1160, -0.0533,  0.0109,
         0.0199

In [ ]:
#최적화 함수
optim = Adam(model.parameters(), lr=0.001)
#몇번 반복할지
epochs = 200
#손실함수
criterion = nn.MSELoss()

for epoch in range(epochs):
    optim.zero_grad() #앞에서 계산했던 기울기를 초기화 하도록

    y_pred = model(x_train)  # 모델 학습시키고 예측값 뽑기   
    loss = criterion(y_pred, y_train)
    #backpropagation
    loss.backward()
    optim.step()

    print("loss:", loss.item())

loss: 84.69347381591797
loss: 104.65826416015625
loss: 84.791748046875
loss: 96.00701904296875
loss: 97.4168701171875
loss: 88.82896423339844
loss: 84.72916412353516
loss: 88.45571899414062
loss: 92.04618835449219
loss: 90.2623291015625
loss: 86.26933288574219
loss: 84.76570129394531
loss: 86.57044982910156
loss: 88.59471893310547
loss: 88.23339080810547
loss: 86.16680908203125
loss: 84.76007843017578
loss: 85.23688507080078
loss: 86.56951141357422
loss: 86.96803283691406
loss: 86.0386734008789
loss: 84.93450164794922
loss: 84.79144287109375
loss: 85.49867248535156
loss: 86.0246353149414
loss: 85.73178100585938
loss: 85.02225494384766
loss: 84.70433807373047
loss: 85.01712799072266
loss: 85.43692016601562
loss: 85.40177917480469
loss: 84.98663330078125
loss: 84.70830535888672
loss: 84.83614349365234
loss: 85.11019897460938
loss: 85.14019012451172
loss: 84.90263366699219
loss: 84.70996856689453
loss: 84.77091217041016
loss: 84.9439468383789
loss: 84.96880340576172
loss: 84.8200531005859

In [106]:
model.state_dict()

OrderedDict([('0.weight',
              tensor([[-0.0900, -0.1399,  0.0442,  ...,  0.1401,  0.1906,  0.2175],
                      [-0.1781,  0.0127, -0.0679,  ..., -0.1667,  0.2448, -0.0388],
                      [-0.0553,  0.1889,  0.1220,  ...,  0.2242,  0.0069,  0.2606],
                      ...,
                      [-0.0055, -0.1373,  0.0927,  ..., -0.0798,  0.2699, -0.0027],
                      [ 0.1717,  0.2257, -0.0815,  ...,  0.0597,  0.1871, -0.2089],
                      [ 0.2108, -0.2018, -0.1713,  ..., -0.2430,  0.2678,  0.2185]])),
             ('0.bias',
              tensor([-0.0945,  0.0294, -0.2611,  0.1480, -0.1373, -0.1358, -0.1339,  0.2422,
                       0.0258,  0.0119, -0.0511, -0.1048,  0.0644,  0.1226,  0.1973,  0.1551,
                      -0.0657, -0.0065, -0.0192,  0.1668,  0.2737, -0.1315,  0.2316, -0.2077,
                       0.0605,  0.2028, -0.3418,  0.1775, -0.0255, -0.0084,  0.0667,  0.1679,
                      -0.2751, -0.2749, 

## GPU 버전

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

#데이터와 모델을 모두 gpu로 올린다
x_train = x_train.to(device)
y_train = y_train.to(device)
model = model.to(device)

#최적화 함수
optim = Adam(model.parameters(), lr=0.001)
#몇번 반복할지
epochs = 200
#손실함수
criterion = nn.MSELoss()

for epoch in range(epochs):
    #앞에서 계산했던 기울기를 0으로 초기화 하도록
    optim.zero_grad() 

    # 모델 학습시키고 예측값 뽑기
    y_pred = model(x_train)
    # 오차값 뽑기  
    loss = criterion(y_pred, y_train)
    
    #오차를 이용해서 backpropagation
    loss.backward()

    #optimizer 이용해서 최적의 가중치 업데이트
    optim.step()

    print("loss:", loss.item())


loss: 84.98959350585938
loss: 88.34917449951172
loss: 91.34169006347656
loss: 86.77369689941406
loss: 85.58769226074219
loss: 88.12107849121094
loss: 86.81924438476562
loss: 85.36104583740234
loss: 86.447509765625
loss: 86.97261810302734
loss: 85.7505111694336
loss: 85.1254653930664
loss: 85.85202026367188
loss: 86.2378158569336
loss: 85.64495849609375
loss: 85.20993041992188
loss: 85.54521942138672
loss: 85.82049560546875
loss: 85.44480895996094
loss: 85.04570007324219
loss: 85.2059326171875
loss: 85.50067901611328
loss: 85.37645721435547
loss: 85.09676361083984
loss: 85.1356201171875
loss: 85.31730651855469
loss: 85.22978210449219
loss: 85.01258850097656
loss: 85.02848052978516
loss: 85.18135070800781
loss: 85.16075897216797
loss: 85.02833557128906
loss: 85.03207397460938
loss: 85.11550903320312
loss: 85.07598876953125
loss: 84.98119354248047
loss: 85.00145721435547
loss: 85.0679931640625
loss: 85.03911590576172
loss: 84.98016357421875
loss: 84.99794006347656
loss: 85.02369689941406
